from django.urls import path
from .api.views import (
     CompanyCreateView,
     CompanyDeleteView,
     CompanyDetailView,
     CompanyUpdateView,
     CompanyListView,
     PersonCreateView,
     PersonDeleteView,
     PersonDetailView,
     PersonUpdateView,
     PersonListView,
     ContactCreateView,
     ContactDeleteView,
     ContactDetailView,
     ContactUpdateView,
     ContactListView,
     BuyerCreateView,
     BuyerDeleteView,
     BuyerDetailView,
     BuyerUpdateView,
     BuyerListView,
     RoleCreateView,
     RoleDeleteView,
     RoleDetailView,
     RoleUpdateView,
     RoleListView,
     EmployeeCreateView,
     EmployeeDeleteView,
     EmployeeDetailView,
     EmployeeUpdateView,
     EmployeeListView,
     CompanyTypeCreateView,
     CompanyTypeDeleteView,
     CompanyTypeDetailView,
     CompanyTypeUpdateView,
     CompanyTypeListView,
     RevenueCreateView,
     RevenueDeleteView,
     RevenueDetailView,
     RevenueUpdateView,
     RevenueListView,
     StatusCreateView,
     StatusDeleteView,
     StatusDetailView,
     StatusUpdateView,
     StatusListView,
     CompanyStatusCreateView,
     CompanyStatusDeleteView,
     CompanyStatusDetailView,
     CompanyStatusUpdateView,
     CompanyStatusListView,
     ActionTypeCreateView,
     ActionTypeDeleteView,
     ActionTypeDetailView,
     ActionTypeUpdateView,
     ActionTypeListView,
     BusinessModelCreateView,
     BusinessModelDeleteView,
     BusinessModelDetailView,
     BusinessModelUpdateView,
     BusinessModelListView,
     IndustryCategoryCreateView,
     IndustryCategoryDeleteView,
     IndustryCategoryDetailView,
     IndustryCategoryUpdateView,
     IndustryCategoryListView,
     ResearchCreateView,
     ResearchDeleteView,
     ResearchDetailView,
     ResearchUpdateView,
     ResearchListView,
     PhotoCreateView,
     PhotoDeleteView,
     PhotoDetailView,
     PhotoUpdateView,
     PhotoListView,
     ActionCreateView,
     ActionDeleteView,
     ActionDetailView,
     ActionUpdateView,
     ActionListView,
)

urlpatterns = [
     path('api/companies/', CompanyListView.as_view(), name='companies_list'),
     path('api/companies/<int:pk>/',
         CompanyDetailView.as_view(), name='company_details'),
     path('api/companies/<int:pk>/delete',
         CompanyDeleteView.as_view(), name='company_delete'),
     path('api/companies/create', CompanyCreateView.as_view(),
         name='company_create'),
     path('api/companies/<int:pk>/update', CompanyUpdateView.as_view(),
         name='company_update'),

     path('api/persons/', PersonListView.as_view(), name='persons_list'),
     path('api/persons/<int:pk>/',
         PersonDetailView.as_view(), name='person_details'),
     path('api/persons/<int:pk>/delete',
         PersonDeleteView.as_view(), name='person_delete'),
     path('api/persons/create', PersonCreateView.as_view(),
         name='person_create'),
     path('api/persons/<int:pk>/update', PersonUpdateView.as_view(),
         name='person_update'),

     path('api/buyers/', BuyerListView.as_view(), name='buyers_list'),
     path('api/buyers/<int:pk>/',
         BuyerDetailView.as_view(), name='buyer_details'),
     path('api/buyers/<int:pk>/delete',
         BuyerDeleteView.as_view(), name='buyer_delete'),
     path('api/buyers/create', BuyerCreateView.as_view(),
         name='buyer_create'),
     path('api/buyers/<int:pk>/update', BuyerUpdateView.as_view(),
         name='buyer_update'),
         
     path('api/roles/', RoleListView.as_view(), name='roles_list'),
     path('api/roles/<int:pk>/',
         RoleDetailView.as_view(), name='role_details'),
     path('api/roles/<int:pk>/delete',
         RoleDeleteView.as_view(), name='role_delete'),
     path('api/roles/create', RoleCreateView.as_view(),
         name='role_create'),
     path('api/roles/<int:pk>/update', RoleUpdateView.as_view(),
         name='role_update'),

     path('api/employees/', EmployeeListView.as_view(), name='employees_list'),
     path('api/employees/<int:pk>/',
         EmployeeDetailView.as_view(), name='employee_details'),
     path('api/employees/<int:pk>/delete',
         EmployeeDeleteView.as_view(), name='employee_delete'),
     path('api/employees/create', EmployeeCreateView.as_view(),
         name='employee_create'),
     path('api/employees/<int:pk>/update', EmployeeUpdateView.as_view(),
         name='employee_update'),

     path('api/companies-types/', CompanyTypeListView.as_view(), name='companies_types_list'),
     path('api/companies-types/<int:pk>/',
         CompanyTypeDetailView.as_view(), name='company_type_details'),
     path('api/companies-types/<int:pk>/delete',
         CompanyTypeDeleteView.as_view(), name='company_type_delete'),
     path('api/companies-types/create', CompanyTypeCreateView.as_view(),
         name='company_type_create'),
     path('api/companies-types/<int:pk>/update', CompanyTypeUpdateView.as_view(),
         name='company_type_update'),

     path('api/revenues/', RevenueListView.as_view(), name='revenues_list'),
     path('api/revenues/<int:pk>/',
         RevenueDetailView.as_view(), name='revenue_details'),
     path('api/revenues/<int:pk>/delete',
         RevenueDeleteView.as_view(), name='revenue_delete'),
     path('api/revenues/create', RevenueCreateView.as_view(),
         name='revenue_create'),
     path('api/revenues/<int:pk>/update', RevenueUpdateView.as_view(),
         name='revenue_update'),

     path('api/statuses/', EmployeeListView.as_view(), name='statuses_list'),
     path('api/statuses/<int:pk>/',
         EmployeeDetailView.as_view(), name='status_details'),
     path('api/statuses/<int:pk>/delete',
         EmployeeDeleteView.as_view(), name='status_delete'),
     path('api/statuses/create', EmployeeCreateView.as_view(),
         name='status_create'),
     path('api/statuses/<int:pk>/update', EmployeeUpdateView.as_view(),
         name='status_update'),
         
     path('api/companies-statuses/', CompanyStatusListView.as_view(), name='companies_statuses_list'),
     path('api/companies-statuses/<int:pk>/',
         CompanyStatusDetailView.as_view(), name='company_status_details'),
     path('api/companies-statuses/<int:pk>/delete',
         CompanyStatusDeleteView.as_view(), name='company_status_delete'),
     path('api/companies-statuses/create', CompanyStatusCreateView.as_view(),
         name='company_status_create'),
     path('api/companies-statuses/<int:pk>/update', CompanyStatusUpdateView.as_view(),
         name='company_status_update'),
         
     path('api/actions-types/', ActionTypeListView.as_view(), name='actions_types_list'),
     path('api/actions-types/<int:pk>/',
         ActionTypeDetailView.as_view(), name='action_type_details'),
     path('api/actions-types/<int:pk>/delete',
         ActionTypeDeleteView.as_view(), name='action_type_delete'),
     path('api/actions-types/create', ActionTypeCreateView.as_view(),
         name='action_type_create'),
     path('api/actions-types/<int:pk>/update', ActionTypeUpdateView.as_view(),
         name='action_type_update'),
         
     path('api/business-models/', BusinessModelListView.as_view(), name='business_models_list'),
     path('api/business-models/<int:pk>/',
         BusinessModelDetailView.as_view(), name='business_model_details'),
     path('api/business-models/<int:pk>/delete',
         BusinessModelDeleteView.as_view(), name='business_model_delete'),
     path('api/business-models/create', BusinessModelCreateView.as_view(),
         name='business_model_create'),
     path('api/business-models/<int:pk>/update', BusinessModelUpdateView.as_view(),
         name='business_model_update'),
         
     path('api/industry-categories/', IndustryCategoryListView.as_view(), name='industry_categories_list'),
     path('api/industry-categories/<int:pk>/',
         IndustryCategoryDetailView.as_view(), name='industry_category_details'),
     path('api/industry-categories/<int:pk>/delete',
         IndustryCategoryDeleteView.as_view(), name='industry_category_delete'),
     path('api/industry-categories/create', IndustryCategoryCreateView.as_view(),
         name='industry_category_create'),
     path('api/industry-categories/<int:pk>/update', IndustryCategoryUpdateView.as_view(),
         name='industry_category_update'),
         
     path('api/researches/', ResearchListView.as_view(), name='researches_list'),
     path('api/researches/<int:pk>/',
         ResearchDetailView.as_view(), name='research_details'),
     path('api/researches/<int:pk>/delete',
         ResearchDeleteView.as_view(), name='research_delete'),
     path('api/researches/create', ResearchCreateView.as_view(),
         name='research_create'),
     path('api/researches/<int:pk>/update', ResearchUpdateView.as_view(),
         name='research_update'),
         
     path('api/photos/', PhotoListView.as_view(), name='photos_list'),
     path('api/photos/<int:pk>/',
         PhotoDetailView.as_view(), name='photo_details'),
     path('api/photos/<int:pk>/delete',
         PhotoDeleteView.as_view(), name='photo_delete'),
     path('api/photos/create', PhotoCreateView.as_view(),
         name='photo_create'),
     path('api/photos/<int:pk>/update', PhotoUpdateView.as_view(),
         name='photo_update'),
                  
     path('api/actions/', ActionListView.as_view(), name='actions_list'),
     path('api/actions/<int:pk>/',
         ActionDetailView.as_view(), name='action_details'),
     path('api/actions/<int:pk>/delete',
         ActionDeleteView.as_view(), name='action_delete'),
     path('api/actions/create', ActionCreateView.as_view(),
         name='action_create'),
     path('api/actions/<int:pk>/update', ActionUpdateView.as_view(),
         name='action_update'),
]