# Generated by Django 2.1.7 on 2020-06-02 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бизнес модель',
                'verbose_name_plural': 'Бизнес модели',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('active', models.BooleanField(verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Юридическое имя')),
                ('abbr_name', models.CharField(max_length=100, verbose_name='Аббревиатура')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='Район')),
                ('postcode', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('employees_number', models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость акций')),
                ('logo', models.CharField(max_length=200, verbose_name='Логотип')),
                ('web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web-сайт')),
                ('foundation_date', models.DateField(verbose_name='Дата основания компании')),
                ('active_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_buyer_companies', to='diplomaBackend.Buyer', verbose_name='Активный покупатель')),
                ('business_models', models.ManyToManyField(to='diplomaBackend.BusinessModel', verbose_name='Бизнес модели')),
                ('buyers', models.ManyToManyField(blank=True, related_name='buyer_companies', to='diplomaBackend.Buyer', verbose_name='Потенциальные покупатели')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статус сделки',
                'verbose_name_plural': 'Статусы сделок',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип компании',
                'verbose_name_plural': 'Типы компаний',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория промышленности',
                'verbose_name_plural': 'Категории промышленности',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Личность',
                'verbose_name_plural': 'Личности',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('reasearch_note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('researcher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researches', to='diplomaBackend.Employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущий')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальный')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальный')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(verbose_name='Номер этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='diplomaBackend.Person', verbose_name='Личность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='diplomaBackend.Role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='diplomaBackend.Person', verbose_name='Личность'),
        ),
        migrations.AddField(
            model_name='companystatus',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_companies_statuses', to='diplomaBackend.Status', verbose_name='Текущий статус сделки'),
        ),
        migrations.AddField(
            model_name='companystatus',
            name='hi_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hi_companies_statuses', to='diplomaBackend.Status', verbose_name='Наивысший статус сделки'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='diplomaBackend.CompanyStatus', verbose_name='Статус сделки'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='diplomaBackend.CompanyType', verbose_name='Тип компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(related_name='contact_companies', to='diplomaBackend.Contact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_categories',
            field=models.ManyToManyField(to='diplomaBackend.IndustryCategory', verbose_name='Категории промышленности'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to='diplomaBackend.Contact', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='diplomaBackend.Company', verbose_name='Родительская компания'),
        ),
        migrations.AddField(
            model_name='company',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='diplomaBackend.Research', verbose_name='Исследования'),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='diplomaBackend.Revenue', verbose_name='Доход'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='diplomaBackend.Person', verbose_name='Личность'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='diplomaBackend.ActionType', verbose_name='Тип действия'),
        ),
    ]
