# Generated by Django 2.1.7 on 2020-06-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplomaBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='research',
        ),
        migrations.RemoveField(
            model_name='companystatus',
            name='hi_status',
        ),
        migrations.AddField(
            model_name='companystatus',
            name='high_status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='high_companies_statuses', to='diplomaBackend.Status', verbose_name='Наивысший статус сделки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_researches', to='diplomaBackend.Company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companystatus',
            name='current_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_companies_statuses', to='diplomaBackend.Status', verbose_name='Текущий статус сделки'),
        ),
        migrations.AlterField(
            model_name='status',
            name='stage_number',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Номер этапа'),
        ),
    ]
