# Generated by Django 2.1.7 on 2020-06-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplomaBackend', '0003_auto_20200603_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='diplomaBackend.Company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
