# Generated by Django 3.0.6 on 2020-06-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomaBackend', '0005_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='current',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Текущий'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Максимальный'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Минимальный'),
        ),
    ]
