# Generated by Django 3.0.6 on 2020-06-09 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplomaBackend', '0006_auto_20200604_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_models',
            field=models.ManyToManyField(related_name='companies', to='diplomaBackend.BusinessModel', verbose_name='Бизнес модели'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry_categories',
            field=models.ManyToManyField(related_name='companies', to='diplomaBackend.IndustryCategory', verbose_name='Категории промышленности'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_companies', to='diplomaBackend.Company', verbose_name='Родительская компания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_as_contact', to='diplomaBackend.Person', verbose_name='Личность'),
        ),
    ]
