# Generated by Django 3.0.6 on 2020-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomaBackend', '0007_auto_20200609_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Стоимость акций'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='current',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Текущий'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Максимальный'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Минимальный'),
        ),
    ]
